<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Models\Country::truncate();

        $items = [
            ['Afghanistan','AF','AFG','',0,4],
            ['Albania','AL','ALB','',0,4],
            ['Algeria','DZ','DZA','',0,4],
            ['American Samoa','AS','ASM','',0,4],
            ['Andorra','AD','AND','',0,4],
            ['Angola','AO','AGO','',0,4],
            ['Anguilla','AI','AIA','',0,4],
            ['Antarctica','AQ','ATA','',0,4],
            ['Antigua and Barbuda','AG','ATG','',0,4],
            ['Argentina','AR','ARG','',0,4],
            ['Armenia','AM','ARM','',0,4],
            ['Aruba','AW','ABW','',0,4],
            ['Australia','AU','AUS','',0,4],
            ['Austria','AT','AUT','',0,4],
            ['Azerbaijan','AZ','AZE','',0,4],
            ['Bahamas','BS','BHS','',0,4],
            ['Bahrain','BH','BHR','',0,4],
            ['Bangladesh','BD','BGD','',0,4],
            ['Barbados','BB','BRB','',0,4],
            ['Belarus','BY','BLR','',0,4],
            ['Belgium','BE','BEL','{firstname} {lastname}\\r\\n{company}\\r\\n{address_1}\\r\\n{address_2}\\r\\n{postcode} {city}\\r\\n{country}',0,4],
            ['Belize','BZ','BLZ','',0,4],
            ['Benin','BJ','BEN','',0,4],
            ['Bermuda','BM','BMU','',0,4],
            ['Bhutan','BT','BTN','',0,4],
            ['Bolivia','BO','BOL','',0,4],
            ['Bosnia and Herzegovina','BA','BIH','',0,4],
            ['Botswana','BW','BWA','',0,4],
            ['Bouvet Island','BV','BVT','',0,4],
            ['Brazil','BR','BRA','',0,4],
            ['British Indian Ocean Territory','IO','IOT','',0,4],
            ['Brunei Darussalam','BN','BRN','',0,4],
            ['Bulgaria','BG','BGR','',0,4],
            ['Burkina Faso','BF','BFA','',0,4],
            ['Burundi','BI','BDI','',0,4],
            ['Cambodia','KH','KHM','',0,4],
            ['Cameroon','CM','CMR','',0,4],
            ['Canada','CA','CAN','',0,4],
            ['Cape Verde','CV','CPV','',0,4],
            ['Cayman Islands','KY','CYM','',0,4],
            ['Central African Republic','CF','CAF','',0,4],
            ['Chad','TD','TCD','',0,4],
            ['Chile','CL','CHL','',0,4],
            ['China 中国','CN','CHN','',0,4],
            ['Christmas Island','CX','CXR','',0,4],
            ['Cocos 0Keeling] Islands','CC','CCK','',0,4],
            ['Colombia','CO','COL','',0,4],
            ['Comoros','KM','COM','',0,4],
            ['Congo','CG','COG','',0,4],
            ['Cook Islands','CK','COK','',0,4],
            ['Costa Rica','CR','CRI','',0,4],
            ['Cote Ivoire','CI','CIV','',0,4],
            ['Croatia','HR','HRV','',0,4],
            ['Cuba','CU','CUB','',0,4],
            ['Cyprus','CY','CYP','',0,4],
            ['Czech Republic','CZ','CZE','',0,4],
            ['Denmark','DK','DNK','',0,4],
            ['Djibouti','DJ','DJI','',0,4],
            ['Dominica','DM','DMA','',0,4],
            ['Dominican Republic','DO','DOM','',0,4],
            ['East Timor','TL','TLS','',0,4],
            ['Ecuador','EC','ECU','',0,4],
            ['Egypt','EG','EGY','',0,4],
            ['El Salvador','SV','SLV','',0,4],
            ['Equatorial Guinea','GQ','GNQ','',0,4],
            ['Eritrea','ER','ERI','',0,4],
            ['Estonia','EE','EST','',0,4],
            ['Ethiopia','ET','ETH','',0,4],
            ['Falkland Islands 0Malvinas]','FK','FLK','',0,4],
            ['Faroe Islands','FO','FRO','',0,4],
            ['Fiji','FJ','FJI','',0,4],
            ['Finland','FI','FIN','',0,4],
            ['France','FR','FRA','',1,4],
            ['French Guiana','GF','GUF','',0,4],
            ['French Polynesia','PF','PYF','',0,4],
            ['French Southern Territories','TF','ATF','',0,4],
            ['Gabon','GA','GAB','',0,4],
            ['Gambia','GM','GMB','',0,4],
            ['Georgia','GE','GEO','',0,4],
            ['Germany','DE','DEU','{company}\\r\\n{firstname} {lastname}\\r\\n{address_1}\\r\\n{address_2}\\r\\n{postcode} {city}\\r\\n{country}',1,4],
            ['Ghana','GH','GHA','',0,4],
            ['Gibraltar','GI','GIB','',0,4],
            ['Greece','GR','GRC','',0,4],
            ['Greenland','GL','GRL','',0,4],
            ['Grenada','GD','GRD','',0,4],
            ['Guadeloupe','GP','GLP','',0,4],
            ['Guam','GU','GUM','',0,4],
            ['Guatemala','GT','GTM','',0,4],
            ['Guinea','GN','GIN','',0,4],
            ['Guinea-Bissau','GW','GNB','',0,4],
            ['Guyana','GY','GUY','',0,4],
            ['Haiti','HT','HTI','',0,4],
            ['Heard and Mc Donald Islands','HM','HMD','',0,4],
            ['Honduras','HN','HND','',0,4],
            ['Hong Kong 香港','HK','HKG','',0,4],
            ['Hungary','HU','HUN','',0,4],
            ['Iceland','IS','ISL','',0,4],
            ['India','IN','IND','',0,4],
            ['Indonesia','ID','IDN','',0,4],
            ['Iran 0Islamic Republic of]','IR','IRN','',0,4],
            ['Iraq','IQ','IRQ','',0,4],
            ['Ireland','IE','IRL','',0,4],
            ['Israel','IL','ISR','',0,4],
            ['Italy','IT','ITA','',0,4],
            ['Jamaica','JM','JAM','',0,4],
            ['Japan','JP','JPN','',0,4],
            ['Jordan','JO','JOR','',0,4],
            ['Kazakhstan','KZ','KAZ','',0,4],
            ['Kenya','KE','KEN','',0,4],
            ['Kiribati','KI','KIR','',0,4],
            ['North Korea','KP','PRK','',0,4],
            ['South Korea','KR','KOR','',0,4],
            ['Kuwait','KW','KWT','',0,4],
            ['Kyrgyzstan','KG','KGZ','',0,4],
            ['Lao Peoples Democratic Republic','LA','LAO','',0,4],
            ['Latvia','LV','LVA','',0,4],
            ['Lebanon','LB','LBN','',0,4],
            ['Lesotho','LS','LSO','',0,4],
            ['Liberia','LR','LBR','',0,4],
            ['Libyan Arab Jamahiriya','LY','LBY','',0,4],
            ['Liechtenstein','LI','LIE','',0,4],
            ['Lithuania','LT','LTU','',0,4],
            ['Luxembourg','LU','LUX','',0,4],
            ['Macau 澳门','MO','MAC','',0,4],
            ['FYROM','MK','MKD','',0,4],
            ['Madagascar','MG','MDG','',0,4],
            ['Malawi','MW','MWI','',0,4],
            ['Malaysia','MY','MYS','',0,4],
            ['Maldives','MV','MDV','',0,4],
            ['Mali','ML','MLI','',0,4],
            ['Malta','MT','MLT','',0,4],
            ['Marshall Islands','MH','MHL','',0,4],
            ['Martinique','MQ','MTQ','',0,4],
            ['Mauritania','MR','MRT','',0,4],
            ['Mauritius','MU','MUS','',0,4],
            ['Mayotte','YT','MYT','',0,4],
            ['Mexico','MX','MEX','',0,4],
            ['Micronesia','FM','FSM','',0,4],
            ['Moldova','MD','MDA','',0,4],
            ['Monaco','MC','MCO','',0,4],
            ['Mongolia','MN','MNG','',0,4],
            ['Montserrat','MS','MSR','',0,4],
            ['Morocco','MA','MAR','',0,4],
            ['Mozambique','MZ','MOZ','',0,4],
            ['Myanmar','MM','MMR','',0,4],
            ['Namibia','NA','NAM','',0,4],
            ['Nauru','NR','NRU','',0,4],
            ['Nepal','NP','NPL','',0,4],
            ['Netherlands','NL','NLD','',0,4],
            ['Netherlands Antilles','AN','ANT','',0,4],
            ['New Caledonia','NC','NCL','',0,4],
            ['New Zealand','NZ','NZL','',0,4],
            ['Nicaragua','NI','NIC','',0,4],
            ['Niger','NE','NER','',0,4],
            ['Nigeria','NG','NGA','',0,4],
            ['Niue','NU','NIU','',0,4],
            ['Norfolk Island','NF','NFK','',0,4],
            ['Northern Mariana Islands','MP','MNP','',0,4],
            ['Norway','NO','NOR','',0,4],
            ['Oman','OM','OMN','',0,4],
            ['Pakistan','PK','PAK','',0,4],
            ['Palau','PW','PLW','',0,4],
            ['Panama','PA','PAN','',0,4],
            ['Papua New Guinea','PG','PNG','',0,4],
            ['Paraguay','PY','PRY','',0,4],
            ['Peru','PE','PER','',0,4],
            ['Philippines','PH','PHL','',0,4],
            ['Pitcairn','PN','PCN','',0,4],
            ['Poland','PL','POL','',0,4],
            ['Portugal','PT','PRT','',0,4],
            ['Puerto Rico','PR','PRI','',0,4],
            ['Qatar','QA','QAT','',0,4],
            ['Reunion','RE','REU','',0,4],
            ['Romania','RO','ROM','',0,4],
            ['Russian Federation','RU','RUS','',0,4],
            ['Rwanda','RW','RWA','',0,4],
            ['Saint Kitts and Nevis','KN','KNA','',0,4],
            ['Saint Lucia','LC','LCA','',0,4],
            ['Saint Vincent and the Grenadines','VC','VCT','',0,4],
            ['Samoa','WS','WSM','',0,4],
            ['San Marino','SM','SMR','',0,4],
            ['Sao Tome and Principe','ST','STP','',0,4],
            ['Saudi Arabia','SA','SAU','',0,4],
            ['Senegal','SN','SEN','',0,4],
            ['Seychelles','SC','SYC','',0,4],
            ['Sierra Leone','SL','SLE','',0,4],
            ['Singapore','SG','SGP','',0,4],
            ['Slovak Republic','SK','SVK','{firstname} {lastname}\\r\\n{company}\\r\\n{address_1}\\r\\n{address_2}\\r\\n{city} {postcode}\\r\\n{zone}\\r\\n{country}',0,4],
            ['Slovenia','SI','SVN','',0,4],
            ['Solomon Islands','SB','SLB','',0,4],
            ['Somalia','SO','SOM','',0,4],
            ['South Africa','ZA','ZAF','',0,4],
            ['South Georgia &amp; South Sandwich Islands','GS','SGS','',0,4],
            ['Spain','ES','ESP','',0,4],
            ['Sri Lanka','LK','LKA','',0,4],
            ['St. Helena','SH','SHN','',0,4],
            ['St. Pierre and Miquelon','PM','SPM','',0,4],
            ['Sudan','SD','SDN','',0,4],
            ['Suriname','SR','SUR','',0,4],
            ['Svalbard and Jan Mayen Islands','SJ','SJM','',0,4],
            ['Swaziland','SZ','SWZ','',0,4],
            ['Sweden','SE','SWE','{company}\\r\\n{firstname} {lastname}\\r\\n{address_1}\\r\\n{address_2}\\r\\n{postcode} {city}\\r\\n{country}',1,4],
            ['Switzerland','CH','CHE','',0,4],
            ['Syrian Arab Republic','SY','SYR','',0,4],
            ['Taiwan 台灣','TW','TWN','',0,1],
            ['Tajikistan','TJ','TJK','',0,4],
            ['Tanzania','TZ','TZA','',0,4],
            ['Thailand','TH','THA','',0,4],
            ['Togo','TG','TGO','',0,4],
            ['Tokelau','TK','TKL','',0,4],
            ['Tonga','TO','TON','',0,4],
            ['Trinidad and Tobago','TT','TTO','',0,4],
            ['Tunisia','TN','TUN','',0,4],
            ['Turkey','TR','TUR','',0,4],
            ['Turkmenistan','TM','TKM','',0,4],
            ['Turks and Caicos Islands','TC','TCA','',0,4],
            ['Tuvalu','TV','TUV','',0,4],
            ['Uganda','UG','UGA','',0,4],
            ['Ukraine','UA','UKR','',0,4],
            ['United Arab Emirates','AE','ARE','',0,4],
            ['United Kingdom','GB','GBR','',1,4],
            ['United States','US','USA','{firstname} {lastname}\\r\\n{company}\\r\\n{address_1}\\r\\n{address_2}\\r\\n{city},{zone} {postcode}\\r\\n{country}',0,4],
            ['United States Minor Outlying Islands','UM','UMI','',0,4],
            ['Uruguay','UY','URY','',0,4],
            ['Uzbekistan','UZ','UZB','',0,4],
            ['Vanuatu','VU','VUT','',0,4],
            ['Vatican City State 0Holy See]','VA','VAT','',0,4],
            ['Venezuela','VE','VEN','',0,4],
            ['Viet Nam','VN','VNM','',0,4],
            ['Virgin Islands 0British]','VG','VGB','',0,4],
            ['Virgin Islands 0U.S.]','VI','VIR','',0,4],
            ['Wallis and Futuna Islands','WF','WLF','',0,4],
            ['Western Sahara','EH','ESH','',0,4],
            ['Yemen','YE','YEM','',0,4],
            ['Democratic Republic of Congo','CD','COD','',0,4],
            ['Zambia','ZM','ZMB','',0,4],
            ['Zimbabwe','ZW','ZWE','',0,4],
            ['Montenegro','ME','MNE','',0,4],
            ['Serbia','RS','SRB','',0,4],
            ['Aaland Islands','AX','ALA','',0,4],
            ['Bonaire','BQ','BES','',0,4],
            ['Curacao','CW','CUW','',0,4],
            ['Palestinian Territory','PS','PSE','',0,4],
            ['South Sudan','SS','SSD','',0,4],
            ['St. Barthelemy','BL','BLM','',0,4],
            ['St. Martin 0French part]','MF','MAF','',0,4],
            ['Canary Islands','IC','ICA','',0,4],
            ['Ascension Island 0British]','AC','ASC','',0,4],
            ['Kosovo','XK','UNK','',0,4],
            ['Isle of Man','IM','IMN','',0,4],
            ['Tristan da Cunha','TA','SHN','',0,4],
            ['Guernsey','GG','GGY','',0,4],
            ['Jersey','JE','JEY','',0,4],
        ];

        foreach($items as $item){
            $insert = [
                'name' => $item[0],
                'iso_code_2' => $item[1],
                'iso_code_3' => $item[2],
                'address_format' => $item[3],
                'postcode_require' => $item[4],
                'status' => $item[5],
            ];
            $cid = App\Models\Country::create($insert)->id;

            if ($insert['iso_code_2'] == 'TW') {
                $zone = [
                    'country_id' => $cid,
                    'name' => '台灣地區',
                    'description' => '台,澎,金,馬',
                ];
                App\Models\GeoZone::create($zone);
            }
        }
    }
}
